name: Tests
on:
  push:
    branches:
      - sync-upstream
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test
    strategy:
      fail-fast: false
      matrix:
        arch: ["arm"]
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: |
        cd examples/tests
        ./run.sh "${{ matrix.arch }}"
